In [5]:
import numpy as np

a = np.array([1,2,3])
print(a)

b = np.array([[9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]])
print(b)
print(b.ndim)


[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]
2


In [6]:
#All 0s matix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [12]:
#Any other number (full_like)
np.full_like(a,4)

array([4, 4, 4])

In [14]:
#Random Decimal Number
np.random.random_sample(a.shape)

array([0.01629839, 0.20881027, 0.71428017])

In [15]:
#Random integer values
np.random.randint(7, size=(3,3))

array([[0, 6, 6],
       [1, 3, 4],
       [4, 0, 5]], dtype=int32)

In [16]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [19]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be Careful When Copying arrays

In [22]:
a = np.array([1,2,3])
b=a.copy()
b[0] = 100
print(a)

[1 2 3]


In [23]:
#Take the sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

####LINEAR ALGEBRA

In [27]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [29]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

Statistics

In [31]:
stats = np.array([1,2,3],[4,5,6])
print(stats)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [32]:
np.min(stats, axis=0)

NameError: name 'stats' is not defined

In [33]:
np.max(stats)

NameError: name 'stats' is not defined

##REORGANIZING ARRAY